# Generated by Django 2.1.7 on 2019-03-22 01:56

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='User Phone Number, example: 09123456790 (Optional)', max_length=11, null=True, unique=True, validators=[dashboard.models.phone_number_validator], verbose_name='Phone Number'),
        ),
    ]
