# Generated by Django 2.1.7 on 2019-03-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190324_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='message',
            field=models.TextField(default='', max_length=1024, verbose_name='message'),
            preserve_default=False,
        ),
    ]
