# Generated by Django 2.1.7 on 2019-03-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_action_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='message',
        ),
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('link created', 'Link Created'), ('link updated', 'Link Updated'), ('link deleted', 'Link Deleted')], default=1, max_length=20, verbose_name='Type of Action'),
            preserve_default=False,
        ),
    ]
