# Generated by Django 2.1.7 on 2019-03-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190324_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('link created', 'Link Created'), ('link updated', 'Link Updated'), ('link deleted', 'Link Deleted'), ('link reported', 'Link Reported')], max_length=20, verbose_name='Type of Action'),
        ),
    ]
