# Generated by Django 2.1.7 on 2019-03-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190325_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('link created', 'Link Created'), ('link updated', 'Link Updated'), ('link reported', 'Link Reported'), ('contact_us', 'Contact Us')], max_length=20, verbose_name='Type of Action'),
        ),
    ]
