# Generated by Django 2.1.7 on 2019-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagram',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
