# Generated by Django 2.1.7 on 2019-03-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='object_slug',
        ),
        migrations.AddField(
            model_name='report',
            name='object_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
