# Generated by Django 2.1.7 on 2019-04-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='group',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='instagram',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='website',
            name='thumbnail',
        ),
    ]
