# Generated by Django 2.1.7 on 2019-03-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190321_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='vip',
        ),
        migrations.RemoveField(
            model_name='group',
            name='vip',
        ),
        migrations.RemoveField(
            model_name='instagram',
            name='vip',
        ),
        migrations.RemoveField(
            model_name='website',
            name='vip',
        ),
    ]
