# Generated by Django 2.1.7 on 2019-03-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20190321_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='page_id',
            field=models.CharField(help_text='without @ simple', max_length=30, verbose_name='Page ID'),
        ),
    ]
